# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gwydionkristoff

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gwydionkristoff.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9304630df00745168e11e618c221490b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61ef2b49d39546d3a6ee8e285ec0bdc7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gwydionkristoff.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9304630df00745168e11e618c221490b }}/gwydionkristoff:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gwydionkristoff'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_40f3a986f4354750ac993883e6402a80 }}
        images: 'gwydionkristoff.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9304630df00745168e11e618c221490b }}/gwydionkristoff:${{ github.sha }}'